# Generated by Django 4.0.1 on 2022-01-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('author', models.TextField(blank=True, max_length=50)),
                ('date_published', models.CharField(blank=True, max_length=20)),
                ('version', models.CharField(blank=True, max_length=4)),
                ('literary_genre', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
