# Generated by Django 4.0.1 on 2022-01-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rest', '0002_remove_book_version_book_editorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(blank=True, max_length=50, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fecha De Publicacion'),
        ),
        migrations.AlterField(
            model_name='book',
            name='editorial',
            field=models.CharField(blank=True, max_length=50, verbose_name='Editorial'),
        ),
        migrations.AlterField(
            model_name='book',
            name='literary_genre',
            field=models.CharField(blank=True, max_length=50, verbose_name='Genero Literario'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titulo'),
        ),
    ]
