# Generated by Django 4.0.1 on 2022-01-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rest', '0003_alter_book_author_alter_book_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=50, verbose_name='Autor'),
        ),
    ]
